import Image from "next/image";
import { ArrowUpRight, Terminal, Cpu, Code2, ScanLine, Layers, ShieldCheck, Check, Zap } from "lucide-react";
import type { Project } from "@/data/projects";

export function ProjectCover({ project, variant = "cover" }: { project: Project; variant?: "cover" | "detail" }) {
  if (project.cover) return <div className="project-cover supplied-cover"><Image src={project.cover} alt={`${project.title} project screenshot`} fill sizes="(max-width: 768px) 100vw, 80vw" /></div>;
  return <div className={`project-cover cover-${project.visual} variant-${variant}`} aria-label={`${project.title} illustrative interface concept`}>
    <div className="concept-label mono">AFX / {project.shortTitle}<span>INTERFACE CONCEPT</span></div>
    <div className="interface-window">
      <div className="window-top"><span className="window-brand">{project.visual === "resume" ? "ResumeX" : project.visual === "shield" ? "SCAM SHIELD" : "AFX"}<i /></span><span className="window-title">{project.shortTitle.toLowerCase().replaceAll(" ", "_")}</span><span className="window-dots">• • •</span></div>
      {project.visual === "suite" ? <div className="suite-preview"><div className="mock-sidebar"><Layers /><Code2 /><Terminal /><Cpu /></div><div className="suite-content"><span className="mock-eyebrow">YOUR NEXT BUILD STARTS HERE</span><h4>Less friction.<br />More creation.</h4><div className="suite-tools">{[["01", "Review code", "Understand every line."], ["02", "Find issues", "Turn signals into solutions."], ["03", "Automate", "Let your workflow work."]].map(([n,t,d]) => <div key={n}><small>{n}</small><strong>{t}</strong><span>{d}</span><ArrowUpRight size={18} /></div>)}</div></div></div>
      : project.visual === "review" ? <div className="review-preview"><div><span className="mock-eyebrow">agent.ts</span><pre><span>01  </span><b>async function</b> buildAgent() {"{"}<br /><span>02  </span>  <b>const</b> context = await retrieve();<br /><span>03  </span>  <b>return</b> model.generate({"{"}<br /><span>04  </span>    context,<br /><span>05  </span>    intent: <em>&quot;build something useful&quot;</em><br /><span>06  </span>  {"}"});<br /><span>07  </span>{"}"}</pre></div><div className="review-note"><Code2 /><small>REVIEW INSIGHT</small><h4>Make every<br />line count.</h4><p>Clear feedback.<br />Better understanding.</p><span className="mock-tag">AI-ASSISTED REVIEW</span></div></div>
      : project.visual === "resume" ? <div className="resume-preview"><div><span className="mock-eyebrow">A NEW CHAPTER</span><h4>Your story.<br />Your next role.</h4><div className="resume-step"><Check size={15} /> About you</div><div className="resume-step"><Check size={15} /> Your experience</div><div className="resume-step current">03 <span>Make it yours</span></div></div><div className="resume-paper"><small>SHAIK ARFAN</small><span>AI Developer · UI/UX Designer</span><b>PROFILE</b><p>Building intelligent digital products<br />with thoughtful interfaces.</p><b>EDUCATION</b><p>B.Tech · NIAT<br />2026 — 2030</p><b>SELECTED WORK</b><p>AFX Dev Suite<br />AFX Code Reviewer</p><b>SKILLS</b><p>AI · Design · Frontend</p></div></div>
      : project.visual === "shield" ? <div className="shield-preview"><ShieldCheck size={76} strokeWidth={1} /><span className="mock-eyebrow">PAUSE. CHECK. PROTECT.</span><h4>A little clarity.<br />A safer next step.</h4><div className="mock-input">Check a link or message <ArrowUpRight size={18} /></div><p>Understand the signals before you act.</p></div>
      : project.visual === "gaming" ? <div className="gaming-preview"><span className="mock-eyebrow">YOUR SESSION. YOUR SETTINGS.</span><div className="gaming-big">PLAY<span>ON.</span></div><div className="gaming-profile"><Zap size={24} /><div><strong>Gaming profile</strong><small>Focused on the next session</small></div><span className="mock-tag">AFX MODE</span></div></div>
      : <div className="system-preview"><div><span className="mock-eyebrow">{project.visual === "driver" ? "KNOW YOUR SYSTEM" : project.visual === "optimizer" ? "MAKE ROOM FOR MORE" : "CLARITY THROUGH DIAGNOSTICS"}</span><h4>{project.visual === "driver" ? <>Every driver.<br />One clear view.</> : project.visual === "optimizer" ? <>A better way<br />to tune your PC.</> : <>Find the issue.<br />See the next step.</>}</h4><span className="mock-tag">{project.tags.join(" / ")}</span></div><div className="system-modules">{(project.visual === "driver" ? ["Display adapter", "Network controller", "Audio device"] : project.visual === "optimizer" ? ["System overview", "Maintenance", "Performance profile"] : ["Environment", "Diagnostics", "Issue overview"]).map((label, i) => <div key={label}><span>{i === 0 ? <Cpu /> : i === 1 ? <ScanLine /> : <Terminal />}</span><strong>{label}</strong><ArrowUpRight size={17} /></div>)}</div></div>}
    </div><div className="cover-footer mono"><span>DESIGNED AROUND THE EXPERIENCE</span><span>2026 / AFX</span></div>
  </div>;
}
